#!/usr/bin/env bash

export PLUGIN_COMMAND_PREFIX="routing"
export PLUGIN_DATA_ROOT="${DOKKU_LIB_ROOT:-/var/lib/dokku}/data/routing"
export PLUGIN_CONTRIB_ROOT="$PLUGIN_DATA_ROOT/contrib"

export DOKKU_BIN="${DOKKU_BIN:-/usr/bin/dokku}"
export DOKKU_ROOT="${DOKKU_ROOT:-/home/dokku}"
export PLUGN_BIN="${PLUGN_BIN:-plugn}"
export DOKKU_NOT_IMPLEMENTED_EXIT="${DOKKU_NOT_IMPLEMENTED_EXIT:-10}"

PLUGIN_BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PLUGIN_BASE_PATH
export PLUGIN_PROVIDER_ROOT="$PLUGIN_BASE_PATH/providers"
